visitorsystem/__init__.py
import os

from flask import Flask, render_template, session
from flask_debugtoolbar import DebugToolbarExtension
from flask_login import LoginManager
from redis import Redis
from werkzeug.utils import redirect

import config
from loggers import log, loggerSet
from visitorsystem.lib.redis_session import RedisSessionInterface
from visitorsystem.models import db, File, Photo, Magazine, MagazineComment, PhotoComment, Comment, Board, \
    Category, \
    Residence, Scuser

# from visitorsystem.views import mail

def create_app(config_name):
    """
    :return: Flask App

    Flask App 생성
    """
    current_dir = os.path.abspath(os.path.dirname(__file__))
    template_folder = os.path.join(current_dir, 'templates')

    application = Flask(__name__, template_folder=template_folder)
    application.jinja_env.auto_reload = True
    application.jinja_env.autoescape = False
    application.jinja_env.add_extension('jinja2.ext.loopcontrols')

    config.init_app(application, config_name)
    db.init_app(application)
    # mail.init_app(application)

    redis = Redis.from_url(application.config['REDIS_URL'])
    application.redis = redis
    application.session_interface = RedisSessionInterface(redis)

    toolbar = DebugToolbarExtension()
    toolbar.init_app(application)

    # admin example
    # admin = Admin(application, name='Happy@Home', template_mode='bootstrap3', index_view=MyAdminIndexView())
    # admin.add_view(UserAdmin(User, db.session, name='사용자관리', endpoint='user'))
    # admin.add_view(ClassAdminCategory(Category, db.session, name='테마', category='분류 관리', endpoint='category'))
    # admin.add_view(ClassAdminResidence(Residence, db.session, name='장소', category='분류 관리', endpoint='residence'))
    # admin.add_view(ClassAdminBusiness(Business, db.session, name='업종', category='분류 관리', endpoint='business'))
    # admin.add_view(ClassAdminPhoto(Photo, db.session, name='포토', category='컨텐츠 관리', endpoint='photo'))
    # admin.add_view(ClassAdminMagazine(Magazine, db.session, name='매거진', category='컨텐츠 관리', endpoint='magazine'))
    # admin.add_view(CommentAdminFile(Comment, db.session, name='댓글', category='댓글 관리', endpoint='comment'))
    # admin.add_view(BoardAdminFile(Board, db.session, name='해피QnA', category='댓글 관리',endpoint='board'))

    # Application Blueprints (내방객 시스템)
    from visitorsystem.views.main import main as main_blueprint
    from visitorsystem.views.user_account import user_account as user_account_blueprint
    from visitorsystem.views.user_auth import user_auth as user_auth_blueprint
    from visitorsystem.views.super_approval import super_approval as super_approval_blueprint
    from visitorsystem.views.common_code import common_code as common_code_blueprint
    from visitorsystem.views.inout_apply import inout_apply as inout_apply_blueprint
    from visitorsystem.views.inout_manage import inout_manage as inout_manage_blueprint
    from visitorsystem.views.inout_apply_manage import inout_apply_manage as inout_apply_manage_blueprint

    from visitorsystem.views.inout_ruleset import inout_ruleset as inout_ruleset_blueprint
    from visitorsystem.views.inout_tag import inout_tag as inout_tag_blueprint
    from visitorsystem.views.statistics import statistics as statistics_blueprint

    application.register_blueprint(main_blueprint)
    application.register_blueprint(user_account_blueprint, url_prefix='/userAccount')
    application.register_blueprint(user_auth_blueprint, url_prefix='/userAuth')
    application.register_blueprint(super_approval_blueprint, url_prefix='/superApproval')
    application.register_blueprint(common_code_blueprint, url_prefix='/commonCode')
    application.register_blueprint(inout_apply_blueprint, url_prefix='/inoutApply')
    application.register_blueprint(inout_manage_blueprint, url_prefix='/inoutManage')
    application.register_blueprint(inout_apply_manage_blueprint, url_prefix='/inoutApplyManage')

    application.register_blueprint(inout_ruleset_blueprint, url_prefix='/inoutRuleset')
    application.register_blueprint(inout_tag_blueprint, url_prefix='/inoutTag')
    application.register_blueprint(statistics_blueprint, url_prefix='/statistics')

    application.errorhandler(403)(lambda e: redirect('/'))
    application.errorhandler(404)(lambda e: render_template('error/404.html'))
    application.errorhandler(500)(lambda e: render_template('error/404.html'))

    # log = ('Redis')
    # handler = logging.StreamHandler(sys.stderr)
    # handler.setFormatter(logging.Formatter('%(name)s - %(levelname)s - %(message)s'))
    # log.addHandler(handler)
    # log.setLevel(logging.INFO)

    login_manager = LoginManager()
    login_manager.init_app(application)
    login_manager.login_view = 'main.login'
    login_manager.login_message = '로그인 후 이용해주세요.'

    loggerSet()

    @login_manager.user_loader
    def load_user(login_id):
        # print(session['id'])
        log("Redis").info("[tenant_id:%s][login_id:%s]", session['ssc_tenant_id'], session['id'])
        return Scuser.query.filter_by(id=session['id']).first()

    return application

visitorsystem/views/apply.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app, session, jsonify
from visitorsystem.forms import TestForm

# 2021-01-25, 출입신청화면개발 by hojunghan
apply = Blueprint('apply', __name__)


@apply.route('/', methods=['GET', 'POST'])
def index():
    # print(request.form)
    # form = TestForm(request.form)
    return render_template(current_app.config['TEMPLATE_THEME'] + '/vms_apply/form.html',
                           current_app=current_app,
                         )

visitorsystem/views/auth.py
from flask import Blueprint, render_template, request, redirect, jsonify, url_for, current_app, session
from sphinx.directives import Author

authes = Blueprint('authes', __name__)

@authes.route('/auth')

visitorsystem/views/inout_apply.py
import boto3
import shortuuid
import json
from datetime import datetime, timedelta
from flask import Blueprint, render_template, request, redirect, url_for, current_app, jsonify, flash
from flask_login import current_user, login_required
from visitorsystem.models import db, Vcapplymaster, Ssctenant, Scrule, Vcvisituser, Sccompinfo, Scuser, Sccode, \
    ScRuleFile, Vcapplyuser, Vcstackuser

inout_apply = Blueprint('inout_apply', __name__)


# 메인페이지
@inout_apply.route('/', methods=['GET', 'POST'])
@login_required
def index():
    tenant_id = current_user.ssctenant.id  # 로그인 사용자의 테넌트 아이디
    biz_id = current_user.biz_id  # 로그인 사용자의 사업자번호
    sccompinfo = db.session.query(Sccompinfo).filter(
        db.and_(Sccompinfo.tenant_id == tenant_id, Sccompinfo.id == biz_id, Sccompinfo.use_yn == '1')).first()
    scrules = db.session.query(Scrule).all()  # 페이지 로드전 동적규칙 조회

    now = datetime.now()
    nextWeek = now + timedelta(weeks=1)
    stime = now.strftime('%m/%d/%Y')
    etime = nextWeek.strftime('%m/%d/%Y')
    return render_template(current_app.config['TEMPLATE_THEME'] + '/inout_apply/section4.html', sccompinfo=sccompinfo,
                           scrules=scrules, stime=stime, etime=etime)


# 방문신청 수정
@inout_apply.route('/<id>', methods=['GET'])
@inout_apply.route('/edit/<id>', methods=['GET'])
def edit(id):
    if request.method == 'GET':
        id = int(id)
        tenant_id = current_user.ssctenant.id  # 로그인 사용자의 테넌트 아이디
        scrules = db.session.query(Scrule).all()  # 페이지 로드전 동적규칙 조회

        # 방문신청마스터 조회
        vcapplymaster = db.session.query(Vcapplymaster).filter(
            db.and_(Vcapplymaster.tenant_id == tenant_id, Vcapplymaster.id == id,
                    Vcapplymaster.use_yn == '1')).first()

        if not vcapplymaster:
            return render_template('error' + '/404.html')

        # 작업자 업체조회
        sccompinfo = db.session.query(Sccompinfo).filter(
            db.and_(Sccompinfo.tenant_id == tenant_id, Sccompinfo.id == vcapplymaster.biz_id,
                    Sccompinfo.use_yn == '1')).first()

        # 접견자 조회
        scuser = db.session.query(Scuser).filter(
            db.and_(Scuser.tenant_id == tenant_id, Scuser.id == vcapplymaster.interview_id,
                    Sccompinfo.use_yn == '1')).first()

        # 방문유형 조회
        visitCategorys = db.session.query(Sccode).filter(
            db.and_(Sccode.tenant_id == tenant_id, Sccode.class_id == 6, Sccode.use_yn == '1')).all()
        catagory = vcapplymaster.visit_category

        # 사업장 조회
        locations = db.session.query(Sccode).filter(
            db.and_(Sccode.tenant_id == tenant_id, Sccode.class_id == 1, Sccode.use_yn == '1')).all()
        site_id = vcapplymaster.site_id
        site_nm = vcapplymaster.site_nm

        # 방문신청시 적용된 rule
        currentRule = []
        for row in db.session.query(Vcvisituser).filter(
                db.and_(Vcvisituser.tenant_id == tenant_id, Vcvisituser.apply_id == id,
                        Vcvisituser.use_yn == '1')).group_by(Vcvisituser.rule_id).all():
            rule_name = db.session.query(Scrule).filter(
                db.and_(Scrule.tenant_id == tenant_id, Scrule.id == row.rule_id)).first().rule_name
            currentRule.append(rule_name)

        # 방문문 조회
        doors = db.session.query(Sccode).filter(
            db.and_(Sccode.tenant_id == tenant_id, Sccode.class_id == 2, Sccode.attb_a == site_id,
                    Sccode.use_yn == '1')).all()
        site_id2 = vcapplymaster.site_id2
        site_nm2 = vcapplymaster.site_nm2

        sdate = vcapplymaster.visit_sdate
        edate = vcapplymaster.visit_edate

        applyDate = {'sdate': sdate.split('-'), 'edate': edate.split('-')}

        applyDate['sdate'] = applyDate['sdate'][1] + '/' + applyDate['sdate'][2] + '/' + applyDate['sdate'][0]
        applyDate['edate'] = applyDate['edate'][1] + '/' + applyDate['edate'][2] + '/' + applyDate['edate'][0]

        state = vcapplymaster.approval_state
        block = ''
        type = 'file'
        event = 'leave'

        if state == '반려' or state == '승인':
            block = 'disabled'
            type = ''
            event = ''


        # 차량종류 조회
        cars = db.session.query(Sccode).filter(
            db.and_(Sccode.tenant_id == tenant_id, Sccode.class_id == 3, Sccode.use_yn == '1')).all()

        # 규칙조회
        vcvisitusers = db.session.query(Vcvisituser).filter(
            db.and_(Vcvisituser.tenant_id == tenant_id, Vcvisituser.apply_id == id, Vcvisituser.use_yn == '1')).all()

        # 방문자조회(Table)

        vcapplyusers = db.session.query(Vcapplyuser).filter(
            db.and_(Vcapplyuser.tenant_id == tenant_id, Vcapplyuser.apply_id == id, Vcapplymaster.use_yn == '1')).all()
        tableList = []

        # 방문신청 하나에 연결된, 사용자리스트 조회
        for vcapplyuser in vcapplyusers:
            obj = {'name': vcapplyuser.visitant, 'phone': vcapplyuser.phone, 'vehicle_type': vcapplyuser.vehicle_type, 'readonly' : '',
                   'vehicle_num': vcapplyuser.vehicle_num, 'rule': []}

            if obj['vehicle_type'] == '차량없음':
                obj['readonly'] = 'readonly'


            for vcvisituser in db.session.query(Vcvisituser).filter(
                    db.and_(Vcvisituser.tenant_id == tenant_id, Vcvisituser.apply_id == id,
                            Vcvisituser.name == obj['name'], Vcvisituser.phone == obj['phone'],
                            Vcvisituser.use_yn == '1')).all():
                dict = {'rule_id': '', 'rule_type': '', 'rule_name': '', 'sdate': '', 'edate': '', 'textDesc': '',
                        'bucketUrl': '', 'fileClassId': ''}
                uuid = 'applyFile' + shortuuid.uuid()  # uuid
                dict['fileClassId'] = uuid
                dict['rule_id'] = vcvisituser.scrule.id
                dict['rule_type'] = vcvisituser.scrule.rule_type
                dict['rule_name'] = vcvisituser.scrule.rule_name
                datechange = vcvisituser.s_date.split('-')
                dict['sdate'] = datechange[1] + '/' + datechange[2] + '/' + datechange[0]
                datechange = vcvisituser.e_date.split('-')
                dict['edate'] = datechange[1] + '/' + datechange[2] + '/' + datechange[0]
                dict['textDesc'] = vcvisituser.text_desc

                if vcvisituser.scrule.rule_type == '파일':
                    scruleFile = db.session.query(ScRuleFile).filter(
                        db.and_(ScRuleFile.tenant_id == tenant_id, ScRuleFile.visit_id == vcvisituser.id,
                                ScRuleFile.use_yn == '1')).first()

                    dict['bucketUrl'] = current_app.config['S3_BUCKET_NAME_VMS'] + scruleFile.s3_url


                obj['rule'].append(dict)

            tableList.append(obj)

            # 방문신청 시점에서 적용된 규칙이름 조회

        return render_template(current_app.config['TEMPLATE_THEME'] + '/inout_apply/edit.html',
                               scrules=scrules, vcapplymaster=vcapplymaster, sccompinfo=sccompinfo, scuser=scuser,
                               applyDate=applyDate, visitCategorys=visitCategorys, catagory=catagory,
                               currentRule=currentRule,
                               locations=locations, site_nm=site_nm, doors=doors, site_nm2=site_nm2, block=block, type=type, event=event,
                               state=state, cars=cars, tableList=tableList)


# 방문신청 수정저장
@inout_apply.route('/save', methods=['POST'])
def save():
    if request.method == 'POST':
        tenant_id = current_user.ssctenant.id  # 테넌트아이디
        applicant_name = request.form['applicant_name']
        applicant_phone = request.form['applicant_phone']

        interviewer_name = request.form['interviewer_name']  # 접견자 이름
        interviewer_phone = request.form['interviewer_phone']  # 접견자 휴대폰번호

        # 접견자 조회(내부직원)
        interViewUser = db.session.query(Scuser).filter(db.and_(Scuser.tenant_id == tenant_id, Scuser.user_type == '0',
                                                                Scuser.name == interviewer_name,
                                                                Scuser.phone == interviewer_phone,
                                                                Scuser.use_yn == '1')).first()

        biz_no = request.form['applicant_biz_no']
        comp_nm = request.form['applicant_comp_nm']
        applyId = request.form['applyId']

        # 업체조회
        sccompinfo = db.session.query(Sccompinfo).filter(
            db.and_(Sccompinfo.tenant_id == tenant_id, Sccompinfo.comp_nm == comp_nm, Sccompinfo.biz_no == biz_no,
                    Sccompinfo.use_yn == '1')).first()

        # STEP01. Vcapplymaster 조회
        vcapplymaster = db.session.query(Vcapplymaster).filter(
            db.and_(Vcapplymaster.tenant_id == tenant_id, Vcapplymaster.id == applyId,
                    Vcvisituser.use_yn == '1')).first()
        db.session.query(Vcvisituser).filter(Vcvisituser.tenant_id == tenant_id,
                                             Vcvisituser.apply_id == applyId).delete()
        db.session.query(Vcapplyuser).filter(Vcapplyuser.tenant_id == tenant_id,
                                             Vcapplyuser.apply_id == applyId).delete()
        if vcapplymaster:
            vcapplymaster.interviewr = request.form['interviewer_name']  # 접견자

            vcapplymaster.applicant = request.form['applicant_name']  # 신청자
            vcapplymaster.applicant_comp_id = request.form['applicant_biz_no']  # 신청자 업체번호
            vcapplymaster.applicant_comp_nm = request.form['applicant_comp_nm']  # 신청자 회사명
            vcapplymaster.phone = request.form['applicant_phone']  # 신청자 휴대폰
            vcapplymaster.visit_category = request.form['inout_purpose_type']  # 방문유형
            vcapplymaster.biz_id = sccompinfo.id  # 업체번호
            vcapplymaster.visit_sdate = request.form['inout_sdate']  # 방문시작일
            vcapplymaster.visit_edate = request.form['inout_edate']  # 방문종료일

visitorsystem/views/statistics.py
from flask import Blueprint, render_template, current_app

statistics = Blueprint('statistics', __name__)


@statistics.route('/')
def index():
    return render_template(current_app.config['TEMPLATE_THEME'] + '/statistics/base.html')

visitorsystem/views/test.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app, session, jsonify
from visitorsystem.forms import TestForm
test = Blueprint('test', __name__)

"""
BLUEPRINT
1.블루프린트 만들기
첫번째 인자(블루프린트이름)

2.main.py에 등록(우리 프로젝트에서는 __init_.py에 등록하면됨)
-from visitorsystem.views.test import test as test_blueprint
 application.register_blueprint(test_blueprint, url_prefix='/test')
 
3.데코레이터 명도 @test로 시작해야한다.
"""


@test.route('/', methods=['GET', 'POST'])
def index():
    print(request.form)
    form = TestForm(request.form)
    return render_template(current_app.config['TEMPLATE_THEME'] + '/test/for.html',
                           current_app=current_app,
                           form=form)
#
# @main.route('/login', methods=['GET', 'POST'])
# def login():
#     form = LoginForm(request.form)
#     if request.method == 'POST':
#         if form.validate():
#             user = User.query.filter_by(email=form.email.data).first()
#             if user:
#                 if not check_password_hash(user.password, form.password.data):
#                     flash('비밀번호가 잘못되었습니다.')
#                 else:
#                     session['user_id'] = user.id
#                     session['user_email'] = user.email
#                     session['user_level'] = user.level
#                     return redirect(request.args.get("next") or url_for('main.index'))
#             else:
#                 flash('회원아이디가 잘못되었습니다.')
#
#     # print('-------------------')
#     # print(Ssctenant.query)
#     # print('-------------------')
#     # ssctenants = Ssctenant.query.all()
#     return render_template(current_app.config['TEMPLATE_THEME'] + '/main/login.html', form=form)

visitorsystem/templates/bootstrap/inout_apply_manage/base.html
{% extends 'bootstrap/base.html' %}

{% block content %}

<link href="{{ url_for('static', filename='css/inout_apply_manage.css') }}" rel="stylesheet">
<script src="{{ url_for('static', filename='js/inout_apply_manage.js') }}" ></script>
<style scoped>
@media only screen and (max-width: 1000px) {
	/* Force table to not be like tables anymore */
	#no-more-tables table,
	#no-more-tables thead,
	#no-more-tables tbody,
	#no-more-tables th,
	#no-more-tables td,
	#no-more-tables tr {
		display: block;
	}

	/* Hide table headers (but not display: none;, for accessibility) */
	#no-more-tables thead tr {
		position: absolute;
		top: -9999px;
		left: -9999px;
	}

	#no-more-tables tr { border: 1px solid #ccc; }

	#no-more-tables td {
		/* Behave  like a "row" */
		border: none;
		border-bottom: 1px solid #eee;
		position: relative;
		padding-left: 50%;
		white-space: normal;
		text-align:left;
	}

	#no-more-tables td:before {
		/* Now like a table header */
		position: absolute;
		/* Top/left values mimic padding */
		top: 6px;
		left: 6px;
		width: 45%;
		padding-right: 10px;
		white-space: nowrap;
		text-align:left;
		font-weight: bold;
	}

	/*
	Label the data
	*/
	#no-more-tables td:before { content: attr(data-title); }
}
</style>

<div id="mainContent">
    {% block modalContent %} {% endblock %}
</div>
{% endblock%}

visitorsystem/templates/bootstrap/inout_apply_manage/list.html
{% extends "bootstrap/inout_apply_manage/apply_modal.html" %}

{% block mainContent %}
<!-- mainContent의 상단 조회조건 설정 부분 -->
<script>
    function url_for(param, searchCondition){
        document.location.href =  "{{url_for( 'inout_apply_manage.index')}}page/" + param + searchCondition;
    }

    function url_for_edit(id){
        document.location.href =  "{{url_for('inout_apply.edit',id='' )}}" + id;
    }





</script>


<div class="mainContent-top">
    <div class="row gap-20 masonry pos-r mR-10" style=" height: 200px;">
        <div class="masonry-sizer col-md-12"></div>
        <div class="masonry-item col-md-12">
            <div class="bgc-white bd p-20 col-md-12">
                <div class="content-top mB-5">
                    <div class="page-header"><h5 class="c-grey-900"> 방문 신청 > 방문 신청 조회 </h5><br></div>
                </div>
                <div class="mT-30">
                </div>
            </div>
            <br>
            <!-- mainContent 최상단 : 페이지 명칭, 버튼 위치-->
            <div class="bgc-white bd p-20">
                <div class="mT-10">
                    <div id="superApprovalSearchForm">
                        <button type="submit" class="btn cur-p btn-primary mB-10 mR-10 btn-right search-btn"
                                id="searchBtn">조회
                        </button>


                        <div class="form-row">
                            <div class="form-group col-md-1">
                                <label class="fw-500" for="applicant_name">신청자</label>
                                <input type="text" class="form-control" name="applicant_name" id="applicant_name"
                                       style="{% if current_user.user_type != '1' %}background-color:white{% endif %}"
                                       value="{% if current_user.user_type == '1' %}{{current_user.name}}{% endif %}"
                                       readonly>
                            </div>

                            <div class="form-group col-md-2">
                                <label class="fw-500" for="applicant_phone">연락처</label>
                                <input type="text" class="form-control" name="applicant_phone" id="applicant_phone"
                                       style="{% if current_user.user_type != '1' %}background-color:white{% endif %}"
                                       value="{% if current_user.user_type == '1' %}{{current_user.phone}}{% endif %}"
                                       readonly>
                            </div>

                            {% if current_user.user_type != '1' %}
                            <div class="form-group col-md-2">
                                <label style="visibility:hidden">&nbsp</label>
                                <button type="button" style="display:block" class="btn btn-primary" data-toggle="modal"
                                        data-target="#visitModal">
                                    <i class="search-icon ti-search pdd-right-10"></i>
                                </button>
                            </div>
                            {% endif %}

                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-4"><label class="fw-500">신청일자</label>
                                <div class="timepicker-input input-icon form-group">
                                    <div class="input-group">
                                        <i class="ti-calendar mT-5 p-5"></i>
                                        <input type="text" class="form-control bdc-grey-200 startDate"
                                               data-provide="datepicker" name="visit_sdate" id="visit_sdate"
                                        >

                                        <h6 class="c-grey-900"> &nbsp~&nbsp</h6>

                                        <i class="ti-calendar mT-5 p-5"></i>
                                        <input type="text" class="form-control bdc-grey-200 ml-20 endDate"
                                               data-provide="datepicker" name="visit_edate" id="visit_edate"
                                        />
                                    </div>
                                </div>
                            </div>

                            <!-- 내부사용자는 해당 검색조건이 보임 -->
                            {% if current_user.user_type != '1' %}
                            <div class="form-group col-md-2"><label for="location">사업장</label>
                                <select id="location" class="form-control" name="site_nm">
                                    <option selected="selected" value="all">-전체-</option>
                                    {% for list in siteList %}
                                    <option name="{{list.code}}" value="{{list.code}}">{{list.code_nm}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            {% endif %}

                            <div class="form-group col-md-2"><label for="inputState">진행상태</label>
                                <select id="inputState" class="form-control" name="approval_state">
                                    <option selected="selected" value="all">-전체-</option>
                                    <option name="승인">승인</option>
                                    <option name="대기">대기</option>
                                    <option name="반려">반려</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-2"><label for="type">방문유형</label>
                                <select id="type" class="form-control" name="visit_category">
                                    <option selected="selected" value="all">-전체-</option>
                                    {% for list in visitCategory %}
                                    <option name="{{list.code_nm}}">{{list.code_nm}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group col-md-3"><label for="visit-purpose">방문목적</label> <input type="text"
                                                                                                            class="form-control"
                                                                                                            id="visit-purpose"
                                                                                                            name="visit_purpose">
                                <input id="visit_purpose" name="visit_purpose" type="hidden" value="hi">
                            </div>

                            <div class="form-group col-md-3"><label for="comp-nm">업체명</label> <input type="text"
                                                                                                     class="form-control"
                                                                                                     id="comp-nm"
                                                                                                     name="comp_nm">
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br/>

<!-- mainContent의 하단 조회결과 테이블 -->
<div class="mainContent-bottom container-fluid">
    <div class="row gap-20 pos-r">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20">

                <h5 class="c-grey-900 mB-20">방문 신청 내역</h5>
                <hr/>
                <section id="no-more-tables">
                    <table id="applyListTable" class="table table-striped table-bordered applyListTable" cellspacing="0"
                           width="100%">
                        <thead>
                        <!-- 변수명 변경 및 컬럼 사이즈 조절 필요함 -->
                        <tr>
                            <th style="width: 80px;" class="numeric">유형</th>
                            <th style="width: 130px;" class="numeric">업체명</th>
                            <th style="width: 230px;" class="numeric">방문목적</th>
                            <th style="width: 120px;" class="numeric">신청자</th>
                            <th style="width: 120px;" class="numeric">방문자 정보</th>
                            <th style="width: 120px;" class="numeric">시작일</th>
                            <th style="width: 120px;" class="numeric">종료일</th>
                            <th style="width: 110px;" class="numeric">신청사업장</th>
                            <th style="width: 110px;" class="numeric">신청출입문</th>
                            <th style="width: 120px;" class="numeric">진행단계</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if lists|length < 1 %}
                        <td colspan="12" style="text-align:center">
                            <text> 조회된 내역이 없습니다.</text>
                        </td>
                        {% else %}
                        <!-- 방문신청마스터에서 작업내역 데이터 출력 부분-->
                        {% for list in lists %}
                        <tr style="cursor:pointer;"
                            onclick="location.href='{{ url_for('inout_apply.edit', id=list.id) }}'">
                            <td data-title="방문유형">{{list.visit_category}}</td>
                            <td data-title="업체명">{{list.sccompinfo.comp_nm}}</td>
                            <td data-title="방문목적">{{list.visit_purpose}}</td>
                            <td data-title="신청자">{{list.applicant}}</td>
                            <td data-title="방문자 정보" style="text-decoration: underline; cursor:pointer;"
                                onclick="event.cancelBubble = true;"
                                data-toggle="modal"
                                class="guestInfo" name="guestInfo" value={{list.id}}>방문자 정보
                            </td>
                            <td data-title="시작일">{{list.visit_sdate}}</td>
                            <td data-title="종료일">{{list.visit_edate}}</td>
                            <td data-title="신청사업장">{{list.site_nm}}</td>
                            <td data-title="신청출입문">{{list.site_nm2}}</td>
                            <td data-title="진행단계">{{list.approval_state}}</td>
                        </tr>
                        {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </section>
                <div id="pagination" class="pagination-nav">
                    {{ func.render_pagination('inout_apply_manage.index', pagination, id=None,
                    query_string=query_string) }}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}