visitorsystem/__init__.py
import os

from flask import Flask, render_template, session
from flask_debugtoolbar import DebugToolbarExtension
from flask_login import LoginManager
from redis import Redis
from werkzeug.utils import redirect

import config
from loggers import log, loggerSet
from visitorsystem.lib.redis_session import RedisSessionInterface
from visitorsystem.models import db, File, Photo, Magazine, MagazineComment, PhotoComment, Comment, Board, \
    Category, \
    Residence, Scuser

# from visitorsystem.views import mail

def create_app(config_name):
    """
    :return: Flask App

    Flask App 생성
    """
    current_dir = os.path.abspath(os.path.dirname(__file__))
    template_folder = os.path.join(current_dir, 'templates')

    application = Flask(__name__, template_folder=template_folder)
    application.jinja_env.auto_reload = True
    application.jinja_env.autoescape = False
    application.jinja_env.add_extension('jinja2.ext.loopcontrols')

    config.init_app(application, config_name)
    db.init_app(application)
    # mail.init_app(application)

    redis = Redis.from_url(application.config['REDIS_URL'])
    application.redis = redis
    application.session_interface = RedisSessionInterface(redis)

    toolbar = DebugToolbarExtension()
    toolbar.init_app(application)

    # admin example
    # admin = Admin(application, name='Happy@Home', template_mode='bootstrap3', index_view=MyAdminIndexView())
    # admin.add_view(UserAdmin(User, db.session, name='사용자관리', endpoint='user'))
    # admin.add_view(ClassAdminCategory(Category, db.session, name='테마', category='분류 관리', endpoint='category'))
    # admin.add_view(ClassAdminResidence(Residence, db.session, name='장소', category='분류 관리', endpoint='residence'))
    # admin.add_view(ClassAdminBusiness(Business, db.session, name='업종', category='분류 관리', endpoint='business'))
    # admin.add_view(ClassAdminPhoto(Photo, db.session, name='포토', category='컨텐츠 관리', endpoint='photo'))
    # admin.add_view(ClassAdminMagazine(Magazine, db.session, name='매거진', category='컨텐츠 관리', endpoint='magazine'))
    # admin.add_view(CommentAdminFile(Comment, db.session, name='댓글', category='댓글 관리', endpoint='comment'))
    # admin.add_view(BoardAdminFile(Board, db.session, name='해피QnA', category='댓글 관리',endpoint='board'))

    # Application Blueprints (내방객 시스템)
    from visitorsystem.views.main import main as main_blueprint
    from visitorsystem.views.user_account import user_account as user_account_blueprint
    from visitorsystem.views.user_auth import user_auth as user_auth_blueprint
    from visitorsystem.views.super_approval import super_approval as super_approval_blueprint
    from visitorsystem.views.common_code import common_code as common_code_blueprint
    from visitorsystem.views.inout_apply import inout_apply as inout_apply_blueprint
    from visitorsystem.views.inout_manage import inout_manage as inout_manage_blueprint
    from visitorsystem.views.inout_apply_manage import inout_apply_manage as inout_apply_manage_blueprint

    from visitorsystem.views.inout_ruleset import inout_ruleset as inout_ruleset_blueprint
    from visitorsystem.views.inout_tag import inout_tag as inout_tag_blueprint
    from visitorsystem.views.statistics import statistics as statistics_blueprint

    application.register_blueprint(main_blueprint)
    application.register_blueprint(user_account_blueprint, url_prefix='/userAccount')
    application.register_blueprint(user_auth_blueprint, url_prefix='/userAuth')
    application.register_blueprint(super_approval_blueprint, url_prefix='/superApproval')
    application.register_blueprint(common_code_blueprint, url_prefix='/commonCode')
    application.register_blueprint(inout_apply_blueprint, url_prefix='/inoutApply')
    application.register_blueprint(inout_manage_blueprint, url_prefix='/inoutManage')
    application.register_blueprint(inout_apply_manage_blueprint, url_prefix='/inoutApplyManage')

    application.register_blueprint(inout_ruleset_blueprint, url_prefix='/inoutRuleset')
    application.register_blueprint(inout_tag_blueprint, url_prefix='/inoutTag')
    application.register_blueprint(statistics_blueprint, url_prefix='/statistics')

    application.errorhandler(403)(lambda e: redirect('/'))
    application.errorhandler(404)(lambda e: render_template('error/404.html'))
    application.errorhandler(500)(lambda e: render_template('error/404.html'))

    # log = ('Redis')
    # handler = logging.StreamHandler(sys.stderr)
    # handler.setFormatter(logging.Formatter('%(name)s - %(levelname)s - %(message)s'))
    # log.addHandler(handler)
    # log.setLevel(logging.INFO)

    login_manager = LoginManager()
    login_manager.init_app(application)
    login_manager.login_view = 'main.login'
    login_manager.login_message = '로그인 후 이용해주세요.'

    loggerSet()

    @login_manager.user_loader
    def load_user(login_id):
        # print(session['id'])
        log("Redis").info("[tenant_id:%s][login_id:%s]", session['ssc_tenant_id'], session['id'])
        return Scuser.query.filter_by(id=session['id']).first()

    return application

visitorsystem/views/apply.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app, session, jsonify
from visitorsystem.forms import TestForm

# 2021-01-25, 출입신청화면개발 by hojunghan
apply = Blueprint('apply', __name__)


@apply.route('/', methods=['GET', 'POST'])
def index():
    # print(request.form)
    # form = TestForm(request.form)
    return render_template(current_app.config['TEMPLATE_THEME'] + '/vms_apply/form.html',
                           current_app=current_app,
                         )

visitorsystem/views/auth.py
from flask import Blueprint, render_template, request, redirect, jsonify, url_for, current_app, session
from sphinx.directives import Author

authes = Blueprint('authes', __name__)

@authes.route('/auth')

visitorsystem/views/statistics.py
from flask import Blueprint, render_template, current_app

statistics = Blueprint('statistics', __name__)


@statistics.route('/')
def index():
    return render_template(current_app.config['TEMPLATE_THEME'] + '/statistics/base.html')

visitorsystem/views/super_approval.py
import datetime
from math import ceil

from flask import Blueprint, current_app, render_template, request, jsonify
from flask_login import current_user
from sqlalchemy import and_

from loggers import log
from visitorsystem.forms import Pagination
from visitorsystem.models import db, Vcapplymaster, Sccode, Sccompinfo, Scrule, Vcvisituser, ScRuleFile, Scclass

super_approval = Blueprint('super_approval', __name__)


@super_approval.route('/', methods=['GET', 'POST'], defaults={'page': 1})
@super_approval.route('/page/<int:page>')
def index(page):
    visitCategory = db.session.query(Sccode).filter(
        and_(Sccode.tenant_id == current_user.ssctenant.id, Sccode.class_id == '6', Sccode.use_yn == '1')).all()

    siteList = db.session.query(Sccode).join(Scclass, Scclass.id == Sccode.class_id) \
        .filter(and_(Scclass.class_cd == 'SITE', Scclass.use_yn == '1',
                     Sccode.tenant_id == current_user.ssctenant.id, Sccode.use_yn == '1')).all()
    today = datetime.datetime.now()
    end_date = today
    start_date = today - datetime.timedelta(days=7)

    searchCondition = {
        'visit_sdate': request.args.get('visit_sdate', str(start_date.strftime('%Y-%m-%d'))),
        'visit_edate': request.args.get('visit_edate', str(end_date.strftime('%Y-%m-%d'))),
        'visit_category': request.args.get('visit_category', 'all'),
        'approval_state': request.args.get('approval_state', 'all'),
        'visit_purpose': request.args.get('visit_purpose', ''),
        'comp_nm': request.args.get('comp_nm', ''),
        'page': request.args.get('page', page),
        'pages': request.args.get('pages', 10),
        'site_id': request.args.get('site_id', 'all')
    }

    searchResult = getApplyListBySearchCondition(searchCondition)
    log("Transaction").info("[tenant_id:%s][login_id:%s]", current_user.ssctenant.id, current_user.id)

    return render_template(current_app.config['TEMPLATE_THEME'] + '/super_approval/list.html',
                           current_app=current_app,
                           visitCategory=visitCategory,
                           lists=searchResult['applyList'],
                           pagination=searchResult['pagination'],
                           query_string=request.query_string.decode('utf-8'),
                           siteList=siteList,
                           userAuth=searchResult['userAuth'])


@super_approval.route('/search', methods=['POST'])
def search():
    if request.method == 'POST':
        # 조회조건에 맞게 조회
        searchResult = getApplyListBySearchCondition(request.form)
        pagination = searchResult['pagination']
        log("Transaction").info("[tenant_id:%s][login_id:%s]", current_user.ssctenant.id, current_user.id)

        lists = []
        for row in searchResult['applyList']:
            results = {
                "id": row.id,
                "comp_nm": row.sccompinfo.comp_nm,
                "visit_category": row.visit_category,
                "visit_purpose": row.visit_purpose,
                "applicant": row.applicant,
                "visit_sdate": row.visit_sdate,
                "visit_edate": row.visit_edate,
                "site_nm": row.site_nm,
                "site_nm2": row.site_nm2,
                "approval_state": row.approval_state,
            }
            lists.append(results)

        page_iter = []
        for page in pagination.iter_pages():
            page_iter.append(page)

        return jsonify({'msg': lists,
                        'listSize': searchResult['listSize'],
                        'pagination': pagination.serializable(page_iter, searchResult['p_pages']),
                        'query_string': "request.query_string.decode('utf-8')",
                        'searchCondition': request.form,
                        'userAuth': searchResult['userAuth']})


@super_approval.route('/save', methods=['POST'])
def save():
    approval_date = request.form['approval_date']
    approval_state = request.form['approval_state']
    lists = request.form.getlist("lists[]")

    # checkList에 포한된 row 승인값 업데이트
    db.session.query(Vcapplymaster).session.query(Vcapplymaster).filter(Vcapplymaster.id.in_(lists),
                                                                        Vcapplymaster.tenant_id == current_user.ssctenant.id) \
        .update({"approval_state": approval_state, "approval_date": approval_date}, synchronize_session=False)
    db.session.commit()

    return jsonify({'msg': '성공적으로 처리되었습니다.',
                    'approval_state': approval_state,
                    'lists': lists})


@super_approval.route('/detail', methods=['POST'])
def detail():
    # 작업 ID에 대한 방문자 명단 상세정보 출력
    id = request.form['id']
    visit_sdate = request.form['sdate']
    visit_edate = request.form['edate']

    # 1. 선택한 작업 ID에 속한 사용자 명단 및 Rule 정보 전체 추출 (Vcstackuser)
    selectApplyInfo = db.session.query(Vcvisituser).join(Scrule, Vcvisituser.rule_id == Scrule.id). \
        filter(and_(Vcvisituser.tenant_id == current_user.ssctenant.id, Vcvisituser.apply_id == id, \
                    Vcvisituser.use_yn == '1', Scrule.use_yn == '1'))

    # 2. 선택한 작업 ID에 포함된 방문자 User 리스트
    users = []
    for row in selectApplyInfo.group_by(Vcvisituser.name, Vcvisituser.phone, Vcvisituser.apply_id,
                                        Vcvisituser.apply_id).all():
        results = {
            "id": row.id,
            "name": row.name,
            "phone": row.phone,
            "apply_id": row.apply_id
        }
        users.append(results)

    # 3. 사용자들의 Rule이 유효한지 판단 및 정보 저장
    bucketUrl = current_app.config['S3_BUCKET_NAME_VMS']

    RuleInfolist = []
    for row in selectApplyInfo.all():
        # 텍스트 필드가 비어있으면, 달력 or 파일
        if row.text_desc == "":
            scrulefile = db.session.query(ScRuleFile).filter(db.and_(ScRuleFile.tenant_id == current_user.ssctenant.id,
                                                                     ScRuleFile.use_yn == '1',
                                                                     ScRuleFile.visit_id == row.id)).first()
            # 규칙의 Type이 바뀌었을 경우, 예전 기록들을 올바르게 조회하기 위함 (변경 전 Type으로)
            # 달력
            if scrulefile == None:
                ruleType = '달력'
                if (visit_sdate >= row.s_date) and (visit_edate <= row.e_date):
                    ruleRes = '가능'
                else:
                    ruleRes = '불가'
            # 파일
            else:
                ruleType = '파일'
                if scrulefile.s3_url != '':
                    ruleRes = '가능'
                    ruleDesc = bucketUrl + scrulefile.s3_url
                else:
                    ruleRes = '불가'
                    ruleDesc = ''
        else:
            ruleType = '텍스트'
            ruleDesc = row.text_desc
            ruleRes = '가능'

        results = {
            "id": row.id,  # User ID
            "apply_id": row.apply_id,  # 방문신청 ID
            "name": row.name,  # 방문자 이름
            "phone": row.phone,  # 방문자 핸드폰
            "rule_id": row.rule_id,  # Rule ID
            "rule_name": row.scrule.rule_name,  # Rule 명칭
            "rule_type": ruleType,  # Rule Type
            "rule_duedate": row.scrule.rule_duedate,  # Rule 기간
            "s_date": row.s_date,  # 달력 Rule 시작일
            "e_date": row.e_date,  # 달력 Rule 종료일
            "ruleRes": ruleRes,  # 규칙이 유효한지 만료인지 표기
            "ruleDesc": ruleDesc  # 텍스트 규칙 or s3 url 입력값
        }
        RuleInfolist.append(results)

    return jsonify({'users': users,
                    'userRuleInfoList': RuleInfolist})


# 조회조건에 맞게 방문신청리스트 SELECT Function
def getApplyListBySearchCondition(searchCondition):
    page = int(searchCondition['page'])
    pages = int(searchCondition['pages'])
    offset = (pages * (page - 1)) if page != 1 else 0

    # 로그인한 사용자 권한에 따른 조회 데이터 변경 (계정당 권한 1개)
    userAuth = current_user.get_auth.code

    # 일반 사용자는 조회는 Data 없도록 하기 위함. (없는 Data Select함으로써 type 형태만 갖춤)
    selectApplyLists = db.session.query(Vcapplymaster)

    # AUTH_ADMIN, AUTH_VISIT_ADMIN : 모든 사업장의 신청내역을 볼 수 있음
    # AUTH_APPROVAL : 본인에게 요청 온 신청내역만 볼 수 있음
    if userAuth == current_app.config['AUTH_ADMIN']:
        selectApplyLists = db.session.query(Vcapplymaster).filter(
            and_(Vcapplymaster.use_yn == '1', Vcapplymaster.tenant_id == current_user.ssctenant.id)) \
            .order_by(Vcapplymaster.id.desc())

    elif userAuth == current_app.config['AUTH_APPROVAL']:
        selectApplyLists = db.session.query(Vcapplymaster).filter(
            and_(Vcapplymaster.use_yn == '1', Vcapplymaster.interview_id == current_user.id,
                 Vcapplymaster.tenant_id == current_user.ssctenant.id)).order_by(Vcapplymaster.id.desc())

    elif userAuth == current_app.config['AUTH_VISIT_ADMIN']:
        selectApplyLists = db.session.query(Vcapplymaster).filter(
            and_(Vcapplymaster.use_yn == '1', Vcapplymaster.tenant_id == current_user.ssctenant.id,
                 Vcapplymaster.site_nm == current_user.site_nm)) \
            .order_by(Vcapplymaster.id.desc())

    # AUTH_ADMIN : 전체관리자 - 사업장 다봐야함
    # AUTH_APPROVAL : 내부직원- 사업장 상관없이 본인에게 온거 다 조회 가능
    # AUTH_VISIT_ADMIN : 방문관리자 - 본인사업장
    if (userAuth == current_app.config['AUTH_ADMIN']) or (userAuth == current_app.config['AUTH_APPROVAL']):
        if searchCondition['site_id'] != "all":
            selectApplyLists = selectApplyLists.filter(Vcapplymaster.site_id == searchCondition['site_id'])
    # elif (userAuth == current_app.config['AUTH_VISIT_ADMIN']):

    # 조회조건에 따른 쿼리
    if searchCondition['visit_category'] != "all":
        selectApplyLists = selectApplyLists.filter(Vcapplymaster.visit_category == searchCondition['visit_category'])
    if searchCondition['approval_state'] != "all":
        selectApplyLists = selectApplyLists.filter(Vcapplymaster.approval_state == searchCondition['approval_state'])
    if searchCondition['visit_purpose'] != '':
        selectApplyLists = selectApplyLists.filter(

visitorsystem/views/test.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app, session, jsonify
from visitorsystem.forms import TestForm
test = Blueprint('test', __name__)

"""
BLUEPRINT
1.블루프린트 만들기
첫번째 인자(블루프린트이름)

2.main.py에 등록(우리 프로젝트에서는 __init_.py에 등록하면됨)
-from visitorsystem.views.test import test as test_blueprint
 application.register_blueprint(test_blueprint, url_prefix='/test')
 
3.데코레이터 명도 @test로 시작해야한다.
"""


@test.route('/', methods=['GET', 'POST'])
def index():
    print(request.form)
    form = TestForm(request.form)
    return render_template(current_app.config['TEMPLATE_THEME'] + '/test/for.html',
                           current_app=current_app,
                           form=form)
#
# @main.route('/login', methods=['GET', 'POST'])
# def login():
#     form = LoginForm(request.form)
#     if request.method == 'POST':
#         if form.validate():
#             user = User.query.filter_by(email=form.email.data).first()
#             if user:
#                 if not check_password_hash(user.password, form.password.data):
#                     flash('비밀번호가 잘못되었습니다.')
#                 else:
#                     session['user_id'] = user.id
#                     session['user_email'] = user.email
#                     session['user_level'] = user.level
#                     return redirect(request.args.get("next") or url_for('main.index'))
#             else:
#                 flash('회원아이디가 잘못되었습니다.')
#
#     # print('-------------------')
#     # print(Ssctenant.query)
#     # print('-------------------')
#     # ssctenants = Ssctenant.query.all()
#     return render_template(current_app.config['TEMPLATE_THEME'] + '/main/login.html', form=form)

visitorsystem/templates/bootstrap/super_approval/base.html
{% extends 'bootstrap/base.html' %}

{% block content %}

<link href="{{ url_for('static', filename='css/super_approval.css') }}" rel="stylesheet">
<script src="{{ url_for('static', filename='js/super_approval.js') }}" ></script>
<style scoped>
@media only screen and (max-width: 1000px) {
	/* Force table to not be like tables anymore */
	#no-more-tables table,
	#no-more-tables thead,
	#no-more-tables tbody,
	#no-more-tables th,
	#no-more-tables td,
	#no-more-tables tr {
		display: block;
	}

	/* Hide table headers (but not display: none;, for accessibility) */
	#no-more-tables thead tr {
		position: absolute;
		top: -9999px;
		left: -9999px;
	}

	#no-more-tables tr { border: 1px solid #ccc; }

	#no-more-tables td {
		/* Behave  like a "row" */
		border: none;
		border-bottom: 1px solid #eee;
		position: relative;
		padding-left: 50%;
		white-space: normal;
		text-align:left;
	}

	#no-more-tables td:before {
		/* Now like a table header */
		position: absolute;
		/* Top/left values mimic padding */
		top: 6px;
		left: 6px;
		width: 45%;
		padding-right: 10px;
		white-space: nowrap;
		text-align:left;
		font-weight: bold;
	}

	/*
	Label the data
	*/
	#no-more-tables td:before { content: attr(data-title); }
}
</style>

<div id="mainContent">
    {% block modalContent %} {% endblock %}
</div>
{% endblock%}

visitorsystem/templates/bootstrap/super_approval/list.html
{% extends "bootstrap/super_approval/approval_modal.html" %}

{% block mainContent %}
<!-- mainContent의 상단 조회조건 설정 부분 -->
<script>
    function url_for(param, searchCondition){
        document.location.href =  "{{url_for( 'super_approval.index')}}page/" + param + searchCondition;
    }


</script>

<div class="mainContent-top">
    <div class="row gap-20 masonry pos-r mR-10" style=" height: 200px;">
        <div class="masonry-sizer col-md-12"></div>
        <div class="masonry-item col-md-12">
            <div class="bgc-white bd p-20 col-md-12">
                <div class="content-top mB-5">
                    <div class="page-header"><h5 class="c-grey-900"> 방문 승인 > 접견자 승인 </h5><br></div>
                </div>
                <div class="mT-30">
                </div>
            </div>
            <br>
            <!-- mainContent 최상단 : 페이지 명칭, 버튼 위치-->
            <div class="bgc-white bd p-20">
                <div class="mT-10">
                    <div id="superApprovalSearchForm">
                        <button type="submit" class="btn cur-p btn-primary mB-10 mR-10 btn-right search-btn"
                                id="searchBtn">조회
                        </button>
                        <div class="form-row">
                            <div class="form-group col-md-4"><label class="fw-500">신청일자</label>
                                <div class="timepicker-input input-icon form-group">
                                    <div class="input-group">
                                        <i class="ti-calendar mT-5 p-5"></i>
                                        <input type="text" class="form-control bdc-grey-200 startDate"
                                               data-provide="datepicker" name="visit_sdate" id="visit_sdate"
                                        >

                                        <h6 class="c-grey-900"> &nbsp~&nbsp</h6>

                                        <i class="ti-calendar mT-5 p-5"></i>
                                        <input type="text" class="form-control bdc-grey-200 ml-20 endDate"
                                               data-provide="datepicker" name="visit_edate" id="visit_edate"

                                        />
                                    </div>
                                </div>
                            </div>

                            <!-- AUTH_ADMIN, AUTH_APPROVAL 권힌 보유자만 해당 검색조건이 보임 -->
                            {% if userAuth == current_app.config['AUTH_ADMIN'] or userAuth ==
                            current_app.config['AUTH_APPROVAL'] %}
                            <div class="form-group col-md-2"><label for="location">사업장</label>
                                <select id="location" class="form-control" name="site_nm">
                                    <option selected="selected" value="all">-전체-</option>
                                    {% for list in siteList %}
                                    <option name="{{list.code}}" value="{{list.code}}">{{list.code_nm}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            {% endif %}

                            <div class="form-group col-md-2"><label for="inputState">진행상태</label>
                                <select id="inputState" class="form-control" name="approval_state">
                                    <option selected="selected" value="all">-전체-</option>
                                    <option name="승인">승인</option>
                                    <option name="대기">대기</option>
                                    <option name="반려">반려</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-2"><label for="type">방문유형</label>
                                <select id="type" class="form-control" name="visit_category">
                                    <option selected="selected" value="all">-전체-</option>
                                    {% for list in visitCategory %}
                                    <option name="{{list.code_nm}}">{{list.code_nm}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group col-md-3"><label for="visit-purpose">방문목적</label> <input type="text"
                                                                                                            class="form-control"
                                                                                                            id="visit-purpose"
                                                                                                            name="visit_purpose">
                                <input id="visit_purpose" name="visit_purpose" type="hidden" value="hi">
                            </div>

                            <div class="form-group col-md-3"><label for="comp-nm">업체명</label> <input type="text"
                                                                                                     class="form-control"
                                                                                                     id="comp-nm"
                                                                                                     name="comp_nm">
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br/>

<!-- mainContent의 하단 조회결과 테이블 -->
<div class="mainContent-bottom container-fluid">
    <div class="row gap-20 pos-r">
        <div class="col-md-12">
            <div class="bgc-white bd bdrs-3 p-20">
                <div class="btn_group">
                    <!--                        data-toggle="modal" data-target="#signModal" -->
                    <button type="button" class="btn cur-p btn-primary mR-10 btn-right modal-btn" id="reject">반려
                    </button>
                    <button type="button" class="btn cur-p btn-primary mR-10 btn-right modal-btn" id="agree">승인</button>
                </div>
                <h5 class="c-grey-900 mB-20">방문 신청 내역</h5>
                <hr/>
                <section id="no-more-tables">
                    <table id="applyListTable" class="table table-striped table-bordered applyListTable" cellspacing="0"
                           width="100%">
                        <thead>
                        <!-- 변수명 변경 및 컬럼 사이즈 조절 필요함 -->
                        <tr>
                            <th style="width: 30px;"><input type="checkbox" id="checkall"/></th>
                            <th style="width: 80px;" class="numeric">유형</th>
                            <th style="width: 130px;" class="numeric">업체명</th>
                            <th style="width: 230px;" class="numeric">방문목적</th>
                            <th style="width: 120px;" class="numeric">신청자</th>
                            <th style="width: 120px;" class="numeric">방문자 정보</th>
                            <th style="width: 120px;" class="numeric">시작일</th>
                            <th style="width: 120px;" class="numeric">종료일</th>
                            <th style="width: 110px;" class="numeric">신청사업장</th>
                            <th style="width: 110px;" class="numeric">신청출입문</th>
                            <th style="width: 120px;" class="numeric">진행단계</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if lists|length < 1 %}
                        <td colspan="12" style="text-align:center">
                            <text> 조회된 내역이 없습니다.</text>
                        </td>
                        {% else %}
                        <!-- 방문신청마스터에서 작업내역 데이터 출력 부분-->
                        {% for list in lists %}
                        <tr>
                            <td data-title="선택"><input type="checkbox" name="chk" value1={{list.id}}
                                                       value2={{list.approval_state}}></td>
                            <td data-title="방문유형">{{list.visit_category}}</td>
                            <td data-title="업체명">{{list.sccompinfo.comp_nm}}</td>
                            <td data-title="방문목적">{{list.visit_purpose}}</td>
                            <td data-title="신청자">{{list.applicant}}</td>
                            <td data-title="방문자 정보" style="text-decoration: underline; cursor:pointer;"
                                data-toggle="modal"
                                class="guestInfo" name="guestInfo" value={{list.id}}>방문자 정보
                            </td>
                            <td data-title="시작일">{{list.visit_sdate}}</td>
                            <td data-title="종료일">{{list.visit_edate}}</td>
                            <td data-title="신청사업장">{{list.site_nm}}</td>
                            <td data-title="신청출입문">{{list.site_nm2}}</td>
                            <td data-title="진행단계">{{list.approval_state}}</td>
                        </tr>
                        {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </section>
                <div id="pagination" class="pagination-nav">
                    {{ func.render_pagination('super_approval.index', pagination, id=None, query_string=query_string) }}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}